# Generated by Django 4.2.4 on 2023-08-05 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('RN', 'Название комнаты'), ('AB', 'Блок с объявлением'), ('EMC', 'Цветная полоса рано утром'), ('MC', 'Цветная полоса утром'), ('DC', 'Цветная полоса днем'), ('EC', 'Цветная полоса вечером'), ('SO', 'Активный вариант ответа'), ('VB', 'Кнопка отправки голоса'), ('V', 'Фиолетовый'), ('DB', 'Темно-синий'), ('YE', 'Желтый'), ('P', 'Розовый'), ('RE', 'Красный'), ('B', 'Синий'), ('G', 'Зеленый'), ('GR', 'Серый'), ('CH', 'Вишневый'), ('OR', 'Оранжевый')], default='RN', max_length=3)),
                ('text', models.CharField(blank=True, max_length=80)),
            ],
        ),
    ]
