# Generated by Django 4.2.4 on 2023-08-05 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Illustration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('L', 'Логотип'), ('IN', 'Приглашение'), ('DA', 'Аватар по умолчанию'), ('DC', 'Обложка по умолчанию'), ('EP', 'Страница с ошибкой'), ('AP', 'Иллюстрация админ-панели')], default='AP', max_length=2)),
                ('file', models.ImageField(upload_to='customization/illustrations/')),
            ],
        ),
        migrations.CreateModel(
            name='Smile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('file', models.ImageField(upload_to='customization/smiles/')),
            ],
        ),
    ]
