# Generated by Django 3.2.6 on 2023-08-21 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_illustration_smile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('email', models.CharField(blank=True, max_length=50)),
                ('city', models.CharField(blank=True, max_length=30)),
                ('avatar', models.ImageField(blank=True, upload_to='members/avatars')),
                ('cover', models.ImageField(blank=True, upload_to='members/covers')),
                ('post_text', models.CharField(blank=True, max_length=5000)),
                ('post_title', models.CharField(blank=True, max_length=50)),
                ('post_image', models.ImageField(blank=True, upload_to='members/postimgs')),
                ('post_created_at', models.DateTimeField(auto_now_add=True)),
                ('color', models.CharField(default='gray', max_length=21)),
                ('webcite', models.CharField(blank=True, max_length=80)),
                ('is_admin', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
