# Generated by Django 3.2.6 on 2023-08-22 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_profile_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_confirm',
            field=models.BooleanField(default=False),
        ),
    ]
