# Generated by Django 3.2.6 on 2023-08-29 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='type',
            field=models.CharField(choices=[('RN', 'Название комнаты'), ('AB', 'Блок с объявлением'), ('EMC', 'Цветная полоса рано утром'), ('MC', 'Цветная полоса утром'), ('DC', 'Цветная полоса днем'), ('EC', 'Цветная полоса вечером'), ('SO', 'Активный вариант ответа'), ('VB', 'Кнопка отправки голоса'), ('CPV', 'Фиолетовый'), ('CPDB', 'Темно-синий'), ('CPYE', 'Желтый'), ('CPP', 'Розовый'), ('CPRE', 'Красный'), ('CPB', 'Синий'), ('CPG', 'Зеленый'), ('CPGR', 'Серый'), ('CPCH', 'Вишневый'), ('CPOR', 'Оранжевый')], default='RN', max_length=4),
        ),
    ]
