# Generated by Django 4.2.4 on 2024-12-07 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_profile_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_active',
        ),
    ]
