# Generated by Django 4.2.4 on 2024-12-20 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_profile_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='StarWarsVoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voices', models.IntegerField(default=0)),
                ('side', models.CharField(choices=[('EM', 'Империя'), ('RP', 'Республика')], default='RP', max_length=2)),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='section',
            field=models.CharField(choices=[('1', 'Концепция и информация'), ('2', 'Руководство по использованию'), ('3', 'Описание кода backend'), ('4', 'Описание кода frontend'), ('5', 'Учебные материалы по организации сообщества'), ('6', 'Учебные материалы для программистов')], default='1', max_length=2),
        ),
    ]
