# Generated by Django 3.2.6 on 2023-09-06 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_profile_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_color',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='api.color'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='post_text',
            field=models.CharField(blank=True, max_length=3000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='webcite',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
