# Generated by Django 4.2.4 on 2025-01-18 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_starwarsvoice_alter_article_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.CharField(max_length=10000),
        ),
    ]
