# Generated by Django 4.2.4 on 2025-01-30 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_answer_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='edited_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='message',
            field=models.TextField(max_length=10000),
        ),
    ]
