# Generated by Django 3.2.6 on 2023-09-06 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_color_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_color',
            new_name='color',
        ),
    ]
