# Generated by Django 4.2.4 on 2025-01-30 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_answer_edited_at_alter_room_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='answer',
            name='edited_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
