# Generated by Django 5.1.6 on 2025-03-05 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_answer_edited_alter_answer_edited_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='system_status',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
