# Generated by Django 4.2.4 on 2023-09-06 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_rename_profile_color_profile_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='is_palette',
            field=models.BooleanField(default=False),
        ),
    ]
