# Generated by Django 3.2.6 on 2023-09-07 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_color_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='color',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.color'),
        ),
    ]
