# Generated by Django 4.2.6 on 2026-01-27 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_chat_message_delete_chatmessage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='participants',
            field=models.ManyToManyField(related_name='chats', to='api.profile', verbose_name='Участники'),
        ),
    ]
