# Generated by Django 3.2.6 on 2023-09-07 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_room_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='color',
        ),
    ]
