# Generated by Django 3.2.6 on 2023-09-07 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_room_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='text',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='color',
            name='type',
            field=models.CharField(choices=[('SC', 'Основной цвет сайта'), ('RN', 'Название комнаты'), ('AB', 'Блок с объявлением'), ('EMC', 'Цветная полоса рано утром'), ('MC', 'Цветная полоса утром'), ('DC', 'Цветная полоса днем'), ('EC', 'Цветная полоса вечером'), ('SO', 'Активный вариант ответа'), ('VB', 'Кнопка отправки голоса'), ('violet', 'Фиолетовый'), ('d_blue', 'Темно-синий'), ('yellow', 'Желтый'), ('pink', 'Розовый'), ('red', 'Красный'), ('blue', 'Синий'), ('green', 'Зеленый'), ('gray', 'Серый'), ('cherry', 'Вишневый'), ('orange', 'Оранжевый')], default='RN', max_length=6),
        ),
        migrations.AlterField(
            model_name='room',
            name='color',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.color'),
        ),
    ]
