# Generated by Django 3.2.6 on 2023-09-07 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20230907_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='text',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
