# Generated by Django 3.2.6 on 2023-09-07 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_color_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='illustration',
            name='file',
        ),
        migrations.AddField(
            model_name='illustration',
            name='text',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
