# Generated by Django 3.2.6 on 2023-09-07 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20230907_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='illustration',
            name='type',
            field=models.CharField(choices=[('L', 'Логотип'), ('IN', 'Приглашение'), ('DA', 'Аватар по умолчанию'), ('DC', 'Обложка по умолчанию'), ('EP', 'Страница с ошибкой'), ('AP', 'Иллюстрация админ-панели'), ('GC', 'Иллюстрация в руководстве')], default='AP', max_length=2),
        ),
    ]
