# Generated by Django 3.2.6 on 2023-09-07 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_illustration_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='illustration',
            name='text',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
