# Generated by Django 3.2.6 on 2023-09-07 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_illustration_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='illustration',
            name='type',
            field=models.CharField(choices=[('L', 'Логотип'), ('IN', 'Приглашение'), ('DA', 'Аватар по умолчанию'), ('DC', 'Обложка по умолчанию'), ('EP', 'Страница с ошибкой'), ('AP', 'Иллюстрация админ-панели'), ('GC', 'Иллюстрация в руководстве'), ('LP', 'Иллюстрация на странице входа'), ('RP', 'Иллюстрация для регистрации')], default='AP', max_length=2),
        ),
    ]
