# Generated by Django 3.2.6 on 2023-09-08 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_alter_illustration_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='viewed',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
