# Generated by Django 3.2.6 on 2023-09-09 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_alter_notification_viewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.color'),
        ),
    ]
