# Generated by Django 3.2.6 on 2023-09-14 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='recipients',
            field=models.ManyToManyField(related_name='recipients', to='api.Profile'),
        ),
    ]
