# Generated by Django 3.2.6 on 2023-09-14 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_alter_notification_recipients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='violator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violator', to='api.profile'),
        ),
    ]
