# Generated by Django 3.2.6 on 2023-09-25 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_roomvoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[(1, 'Концепция'), (2, 'Руководство по использованию'), (3, 'Описание кода backend'), (4, 'Описание кода frontend'), (5, 'Учебные материалы по организации сообщества'), (6, 'Учебные материалы для программистов')], default=1, max_length=2)),
                ('name', models.CharField(max_length=150)),
                ('text', models.TextField(max_length=15000)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.profile')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleIllustration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=150)),
                ('file', models.ImageField(blank=True, upload_to='illustrations')),
                ('article', models.ForeignKey(blank='True', default=None, on_delete=django.db.models.deletion.CASCADE, to='api.article')),
            ],
        ),
    ]
