# Generated by Django 3.2.6 on 2023-09-25 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_article_articleillustration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='section',
            field=models.CharField(choices=[('1', 'Концепция'), ('2', 'Руководство по использованию'), ('3', 'Описание кода backend'), ('4', 'Описание кода frontend'), ('5', 'Учебные материалы по организации сообщества'), ('6', 'Учебные материалы для программистов')], default='1', max_length=2),
        ),
    ]
