# Generated by Django 3.2.6 on 2023-09-25 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_alter_article_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleillustration',
            name='article',
            field=models.ForeignKey(blank='True', default=None, on_delete=django.db.models.deletion.CASCADE, related_name='illustrations', to='api.article'),
        ),
    ]
