# Generated by Django 3.2.6 on 2023-10-02 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_room_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='type',
            field=models.CharField(choices=[('CMN', 'Общие'), ('ADM', 'Административные'), ('OFC', 'Служебные')], default='CMN', max_length=3),
        ),
    ]
