# Generated by Django 3.2.6 on 2023-10-02 12:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0048_alter_room_saved_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='saved_by',
            field=models.ManyToManyField(blank='True', to=settings.AUTH_USER_MODEL),
        ),
    ]
