# Generated by Django 3.2.6 on 2023-10-02 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_alter_room_saved_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='saved_by',
            field=models.ManyToManyField(blank='True', to='api.Profile'),
        ),
    ]
