# Generated by Django 3.2.6 on 2023-10-03 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_alter_room_saved_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='saved_by',
            field=models.ManyToManyField(blank='True', to='api.Profile'),
        ),
    ]
