# Generated by Django 3.2.6 on 2023-10-03 14:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_alter_poll_saved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='voice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
