# Generated by Django 3.2.6 on 2023-10-03 14:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0052_voice_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='saved_by',
            field=models.ManyToManyField(blank='True', to=settings.AUTH_USER_MODEL),
        ),
    ]
