# Generated by Django 3.2.6 on 2023-10-04 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_alter_poll_saved_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customization',
            name='type',
            field=models.CharField(choices=[('CN', 'Название сайта'), ('AN', 'Объявление'), ('RL', 'Правила'), ('SD', 'Описание сайта'), ('CT', 'Контакты')], default='AN', max_length=2),
        ),
    ]
