# Generated by Django 3.2.6 on 2023-10-04 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_alter_customization_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customization',
            name='text',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
